# APP REPO CI - poc-a-node
# Calls the central reusable workflow in poc-central-pipelines.

name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI
    uses: NTTData-HybridCloud/poc-central-pipelines/.github/workflows/node-ci.yml@main
    with:
      project-name: poc-node-app
    secrets: inherit
